name: NDX Alerts

on:
  schedule:
    - cron: "0 * * * *"  # chaque heure UTC
  workflow_dispatch:

concurrency:
  group: ndx-alerts
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      TG_TOKEN:        ${{ secrets.TG_TOKEN }}
      TG_CHAT:         ${{ secrets.TG_CHAT }}
      FINNHUB_TOKEN:   ${{ secrets.FINNHUB_TOKEN }}
      SYMBOL_PRICE:    ${{ vars.SYMBOL_PRICE }}
      CAPITAL_USD:     ${{ vars.CAPITAL_USD }}
      DASHBOARD_URL:   ${{ vars.DASHBOARD_URL }}
      NEWS_WINDOW_MIN: ${{ vars.NEWS_WINDOW_MIN }}
      SHORT_ALLOWED:   ${{ vars.SHORT_ALLOWED }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps (pinned)
        run: |
          pip install --no-cache-dir \
            yfinance==0.2.44 pandas==2.2.2 numpy==1.26.4 \
            pytz==2024.1 requests==2.32.3 python-dateutil==2.9.0.post0 \
            holidays==0.55 feedparser==6.0.11 pandas-datareader==0.10.0

      - name: Debug env
        run: |
          python -V
          pip freeze | grep -E "yfinance|pandas|numpy|feedparser|datareader"
          ls -la

      - name: Run alerts
        run: python ndx_alerts.py

      # Par sécurité: ne marque pas le workflow en failure si l'étape Python renvoie ≠0
      - name: Soft-fail guard
        if: failure()
        run: echo "::warning::Workflow marked success despite step failure (handled by bot)."
