name: NDX Alerts

on:
  schedule:
    - cron: "0 * * * *"   # tourne chaque heure (UTC). Le script n'envoie qu'aux heures Paris définies.
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      TG_CHAT:  ${{ secrets.TG_CHAT }}
      SYMBOL_PRICE: ${{ vars.SYMBOL_PRICE }}   # ex: ^NDX ou QQQ (optionnel)
      CAPITAL_USD:  ${{ vars.CAPITAL_USD }}    # ex: 100000 (optionnel)
      DASHBOARD_URL: ${{ vars.DASHBOARD_URL }} # URL GitHub Pages/Netlify (optionnel)
      NEWS_WINDOW_MIN: ${{ vars.NEWS_WINDOW_MIN }} # ex: 180 (optionnel)

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install deps (pinned)
        run: |
          pip install --no-cache-dir \
            yfinance==0.2.44 pandas==2.2.2 numpy==1.26.4 \
            pytz==2024.1 requests==2.32.3 python-dateutil==2.9.0.post0 \
            holidays==0.55 feedparser==6.0.11 pandas-datareader==0.10.0

      - name: Run alerts
        run: python ndx_alerts.py
